CREATE TABLE song ( op_id VARCHAR(50), song_name VARCHAR(50), artist VARCHAR(50), PRIMARY KEY(op_id));
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op1', 'Can Do', 'Gran Rodeo' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op2', 'RIMFIRE', 'Gran Rodeo' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op3', 'The Other Self', 'Gran Rodeo' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op4', 'Ever-changing Magical Star', 'Gran Rodeo' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op5', 'Punky Funky Love', 'Gran Rodeo' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kurobas_op6', 'Zero', 'Kenshou Ono' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'utapri_op1', 'Orpheus', 'Miyano Mamoru' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'utapri_op2', 'Canon', 'Miyano Mamoru' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'utapri_op3', 'The dice are cast', 'QUARTET NIGHT' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'ansatsu_op1', 'Seishun Satsubatsu-ron', '3-E Utatan' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'ansatsu_op2', 'Jiryoku Hongan Revolution', '3-E Utatan' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'owari_op1', 'XU', 'Gemie' );
INSERT INTO song ( op_id, song_name, artist ) VALUES ( 'kekkai_op1', 'Hello, World!', 'Bump of Chicken' );